### ISSUE TITLE
Suggestion - going barefoot doesn't trample crops

### ISSUE THREAD

**Issue by anoomolu** [Darkhax-Minecraft/Trample-No-More#4]
Hi! Really useful mod, it just makes sense that Feather Falling makes you not disturb nearby crops.

I added "minecraft:air" to the softboots tag in the hopes that wearing no boots would prevent trampling (like treading lightly between plants), but unfortunately that wasn't what ended up happening. Would it be possible to add this functionality? 

Thank you either way ^^

**Comment by Darkhax** [comment]
This is definitely a feature I would consider, although probably have it turned off by default. Which version of Minecraft are you using?

**Comment by anoomolu** [comment]
I'm on Fabric 1.20.1

**Comment by Darkhax** [comment]
Sorry this took so long. This has been added in the [13.0.3](https://www.curseforge.com/minecraft/mc-mods/trample-no-more/files/5127308) update which is currently being processed by CurseForge. This feature has also been added to 1.20.4 in the 16.0.4 update. 

This feature is disabled by default but can easily be enabled using the config file. Run the game at least once with the update installed and then look inside your config folder for a `tramplenomore.json` file. When you edit it with a text editor it should look like this. Simply set `"barefoot": false"` to `"barefoot": true`.

```json
{
  "featherFalling": true,
  "taggedItems": true,
  "taggedEntities": true,
  "creativeMode": true,
  "barefoot": true
}
```
